'''
originally generated by "django-admin startapp" using Django 2.1.7 for the app "hospitals";
it sets the default configuration of this app;
@author: Zhao Jichen and Ye Yifan
'''

default_app_config = 'hospitals.apps.HospitalsConfig'