'''
hospitals/__init__.py:
originally generated by "django-admin startapp" using Django 2.1.2 for the app "hospitals"
it sets the default configuration of this app

created on 23 October, 2018

@author: Zhao Jichen and Ye Yifan
'''

default_app_config = 'hospitals.apps.HospitalsConfig'