'''
originally generated by "django-admin startapp" using Django 2.1.7 for the app "hospitals";
it contains the configuration of this app;
@author: Zhao Jichen and Ye Yifan
'''

from django.apps import AppConfig


class HospitalsConfig(AppConfig):
    '''
    Set the name of this app.
    '''
    
    name = 'hospitals'
    verbose_name = 'Medical Service'