'''
project environment management originally generated by "django-admin startproject" using Django 2.1.7 for the system;
@author: Liu Haodong, Zhao Jichen, Ye Yifan, and Wang Annong
'''

import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "PRS.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Failed to import Django!"
            "Are you sure that it is installed and available on your PYTHONPATH environment variable?"
            "Did you forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)