# Generated by Django 2.1.2 on 2018-11-09 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_departmentinfo_doctorinfo_hospitalinfo_registrationinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.DepartmentInfo', verbose_name='workplace'),
        ),
        migrations.AddField(
            model_name='doctorinfo',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.HospitalInfo', verbose_name='hospital'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentinfo',
            unique_together={('name', 'belong_to')},
        ),
    ]
