'''
Django settings originally generated by "django-admin startproject" using Django 2.1.7 for the system;
@author: Liu Haodong, Zhao Jichen, Ye Yifan, and Wang Annong
'''

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # build paths inside the project like this: os.path.join(BASE_DIR, ...)

# quick-start development settings - unsuitable for production
SECRET_KEY = '3+cbzdqfu5%w&lri8htvcrx_7dkv4@9ye^5#&#dxtjh*^d0px-'  # SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True  # SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = []
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

# application definition
INSTALLED_APPS = [
    'users',
    'hospitals',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'xadmin',
    'crispy_forms',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'PRS.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # the media processor for "{{ MEDIA_URL }}" on some HTML pages in the templates
            ],
        },
    },
]
WSGI_APPLICATION = 'PRS.wsgi.application'

# database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# use the following email settings to send a verification link
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'teamgprs@outlook.com'
EMAIL_HOST_PASSWORD = 'SHIELDadmin007_zjc'
EMAIL_USE_TLS = True

# internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# overload AUTH_USER_MODEL
AUTH_USER_MODEL = 'users.UserProfile'

# static files (CSS, JavaScript, and images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# storage path for files uploaded
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')   # the root directory