'''
URL configuration originally generated by "django-admin startproject" using Django 2.1.2 for the PRS project

Django 2.1.2:
--Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
--For more information, see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

created on 16 October, 2018

@author: Liu Haodong, Zhao Jichen, Ye Yifan, and Wang Annong
'''

from . import views;

import xadmin
from django.urls import path, include, re_path
from django.views.static import serve
from PRS.settings import MEDIA_ROOT
from users.views import LoginView, ActiveUserView, RegisterView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView

#the "urlpatterns" list routes URLs to views
urlpatterns = [
    path( 'me/', xadmin.site.urls ),  #Xadmin
    path( '', views.home, name = 'index' ),  #the home page
    path( 'home/', views.home, name = 'home' ),  #the home page
    path( 'reg/', views.reg, name = 'reg' ),  #the registration page
    path( 'reg/data_refresh/', views.data_refresh, name = 'data_refresh' ),  #the registration page with real-time updated data
    path( 'reg/rec_reg/', views.rec_reg, name = 'rec_reg' ),  #the registration result page
    path( 'about/', views.about, name = 'about' ),  #the system introduction page
    path( 'login/', LoginView.as_view(), name = 'login' ),  #the login page
    path( 'sign-up/', RegisterView.as_view(), name = 'sign-up' ),  #the sigh-up page
    re_path( r'^media/(?P<path>.*)', serve, { 'document_root': MEDIA_ROOT } ),  #the media resource management url
    path( 'captcha/', include( 'captcha.urls' ) ),  #the captcha resource management url
    re_path( 'active/(?P<active_code>.*)/', ActiveUserView.as_view(), name = 'user_active' ),  #the page showing after activating successfully
    path( 'forget/', ForgetPwdView.as_view(), name = 'forget_pwd'),  #the page for asking for resetting the password
    re_path( 'reset/(?P<active_code>.*)/', ResetView.as_view(), name = 'reset_pwd' ),  #the page for resetting the password
    path( 'modify_pwd/', ModifyPwdView.as_view(), name = 'modify_pwd' ),  #the page for modifying the password
    path( 'logout/', LogoutView.as_view(), name = "logout" ),  #the logout page
]