'''
WSGI configuration originally generated by "django-admin startproject" using Django 2.1.7 for the system;
this module exposes the WSGI callable as a module-level variable named "application";
@author: Liu Haodong, Zhao Jichen, Ye Yifan, and Wang Annong
'''

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'PRS.settings')
application = get_wsgi_application()