'''
WSGI configuration originally generated by "django-admin startproject" using Django 2.1.2 for the PRS project
this module exposes the WSGI callable as a module-level variable named "application"

Django 2.1.2:
For more information on this file, see:
    https://docs.djangoproject.com/en/2.1/howto/deployment/wsgi/

created on 16 October, 2018

@author: Liu Haodong, Zhao Jichen, Ye Yifan, and Wang Annong
'''

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault( 'DJANGO_SETTINGS_MODULE', 'PRS.settings' )

application = get_wsgi_application()