'''
users/__init__.py:
originally generated by "django-admin startapp" using Django 2.1.2 for the app "users"
it sets the default configuration of this app

created on 23 October, 2018

@author: Liu Haodong and Wang Annong
'''

default_app_config = 'users.apps.UsersConfig'