'''
originally generated by "django-admin startapp" using Django 2.1.7 for the app "users";
it sets the default configuration of this app;
@author: Liu Haodong and Wang Annong
'''

default_app_config = 'users.apps.UsersConfig'