'''
users/apps.py:
originally generated by "django-admin startapp" using Django 2.1.2 for the app "users"
it contains the configuration of this app

created on 23 October, 2018

@author: Liu Haodong and Wang Annong
'''

from django.apps import AppConfig


class UsersConfig( AppConfig ):
    '''
    Set the name of this app.
    '''
    
    name = 'users'
    verbose_name = 'User Centre'