'''
originally generated by "django-admin startapp" using Django 2.1.7 for the app "users";
it contains the configuration of this app;
@author: Liu Haodong and Wang Annong
'''

from django.apps import AppConfig


class UsersConfig(AppConfig):
    '''
    Set the name of this app.
    '''
    
    name = 'users'
    verbose_name = 'User Centre'